// env.example.js — Environment variable template
// Copy this file to env.js and fill in the values.
// env.js is excluded from git — it is generated by GitHub Actions from repository Secrets.
//
// For local development:
//   cp js/env.example.js js/env.js
//   (values are already filled with defaults below)

window.__ASTN_ENV__ = {
  // Master secret for .astn AES-256-GCM key derivation (PBKDF2)
  // Must match the app's AstnCryptoService.ets constant
  MASTER_SECRET: 'AstNovel_ASTN_v2_MasterSecret_Key_2026'
};
